# local path specified in spec must exist on target node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-broker-2
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-broker
  local:
    path: /mnt/disks/broker2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          # replace with hostname-2
          - my-node-2
