---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-broker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi 
  storageClassName: kafka-broker
