---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: kafka-zookeeper
