---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: burrow
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        burrow-tag: "latest"
        burrow-exporter-tag: "latest"
        burrow-dashboard-tag: "latest"
    spec:
      containers:
      - name: burrow
        image: solsson/burrow@sha256:6b9e1ed658e3c3aa572b907701311a8ff1bb341d47275d94dfe7dc2c8839d9e1
        ports:
        - name: api
          containerPort: 8000
        readinessProbe:
          httpGet:
            path: /burrow/admin
            port: 8000
        livenessProbe:
          httpGet:
            path: /burrow/admin
            port: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/burrow
      - name: exporter
        image: solsson/burrow-exporter@sha256:7db7cb4d09df51c786c338d1a60d57b02f69efed294e4db68c1c5ba04d22a3a8
        ports:
        - name: prometheus
          containerPort: 8080
        env:
        - name: BURROW_ADDR
          value: http://localhost:8000
        - name: API_VERSION
          value: "3"
        - name: METRICS_ADDR
          value: 0.0.0.0:8080
        - name: INTERVAL
          value: "30"
      - name: dashboard
        image: joway/burrow-dashboard@sha256:d36cd7525b60e9dde7eac2c4bb98c13de439eef99abf1272bebf6bca9b48f9a4
        env:
          - name: BURROW_BACKEND
            value: http://localhost:8000
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: burrow-config
