apiVersion: batch/v1
kind: Job
metadata:
  name: preferred-replica-election
  namespace: kafka
spec:
  template:
    metadata:
      name: preferred-replica-election
    spec:
      containers:
      - name: kafka
        image: reddone/kafka:1.0@sha256:20ed8677c465a749c4d97a023204111833fa3c5ce66021647331d9493f4f8ec2
        command:
        - ./bin/kafka-preferred-replica-election.sh
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
  backoffLimit: 3
