---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: avro-schemas
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: schema-registry
      annotations:
        kafka-cp-tag: "1.0"
    spec:
      containers:
      - name: cp
        image: reddone/kafka-cp@sha256:561caf11d2f44dda2b074c9265dc89c2869e5b178936c88209852e22e4d005bf
        env:
        - name: SCHEMA_REGISTRY_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/schema-registry/log4j.properties
        command:
        - schema-registry-start
        - /etc/schema-registry/schema-registry.properties
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/schema-registry
      volumes:
      - name: config
        configMap:
          name: avro-tools-config
