---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-zookeeper
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
